version: '2'
services:
  drupal:
    image: drupal:latest
    ports:
      - '8080:80' # expose 8080 on host and sent to 80 in container
    volumes:
      - ./drupal:/var/www/html
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
      POSTGRES_DB: drupal
volumes:
  drupal:
    driver: local
  postgres:
    driver: local